project_name: blinkgo

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...

snapshot:
  name_template: "{{ .Tag }}"

builds:
  - skip: true
  - id: "{{ .ProjectName }}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_arm_5
      - linux_arm_7
      - linux_amd64
      - linux_arm64
      - windows_386
      - windows_amd64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - '*.txt'
    allow_different_binary_count: true

universal_binaries:
  - replace: true